--ADD COLUNA A TABELA
ALTER TABLE TB_CAIXA ADD SALDO FLOAT;
ALTER TABLE TB_PAGAMENTO ADD PRAZO INT;
ALTER TABLE TB_PARCEIRO ADD UF CHAR(2);
ALTER TABLE TB_PARCEIRO ADD ATIVO CHAR(1);
ALTER TABLE TB_ITENS ADD VALOR_DESCONTO FLOAT;
ALTER TABLE TB_VENDAS ADD ID_EMPRESA INT;
ALTER TABLE TB_FINANCEIRO ADD ID_EMPRESA INT;
ALTER TABLE TB_FINANCEIRO ADD ID_CLIENTE INT;
ALTER TABLE TB_FINANCEIRO ADD OBSERVACAO VARCHAR2(1000);
ALTER TABLE TB_ESTOQUE ADD VALOR_CUSTO FLOAT;

--RENOMEAR COLUNA
ALTER TABLE TB_PARCEIRO RENAME COLUMN TIPO_PARCEITO TO TIPO_PARCEIRO;
