--ADD FOREIGN KEY 
ALTER TABLE TB_AGENDA ADD CONSTRAINT FK_AGENDA_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIO (ID_USUARIO);
ALTER TABLE TB_ITENS ADD CONSTRAINT FK_ITENS_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES TB_PRODUTO (ID_PRODUTO);
ALTER TABLE TB_VENDAS ADD CONSTRAINT FK_VENDAS_EMPRESA FOREIGN KEY (ID_EMPRESA) REFERENCES TB_EMPRESA (ID_EMPRESA);
ALTER TABLE TB_VENDAS ADD CONSTRAINT FK_VENDAS_PAGAMENTO FOREIGN KEY (ID_PAGAMENTO) REFERENCES TB_PAGAMENTO (ID_PAGAMENTO);
ALTER TABLE TB_VENDAS ADD CONSTRAINT FK_VENDAS_PARCEIRO FOREIGN KEY (ID_CLIENTE) REFERENCES TB_PARCEIRO (ID_CLIENTE);
ALTER TABLE TB_FINANCEIRO ADD CONSTRAINT FK_FINANCEIRO_PAGAMETO FOREIGN KEY (ID_PAGAMENTO) REFERENCES TB_PAGAMENTO (ID_PAGAMENTO);
ALTER TABLE TB_FINANCEIRO ADD CONSTRAINT FK_FINANCEIRO_EMPRESA FOREIGN KEY (ID_EMPRESA) REFERENCES TB_EMPRESA (ID_EMPRESA);
ALTER TABLE TB_FINANCEIRO ADD CONSTRAINT FK_FINANCEIRO_PARCEIRO FOREIGN KEY (ID_CLIENTE) REFERENCES TB_PARCEIRO (ID_CLIENTE);
ALTER TABLE TB_ESTOQUE ADD CONSTRAINT FK_ESTOQUE_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES TB_PRODUTO (ID_PRODUTO);
ALTER TABLE TB_ESTOQUE ADD CONSTRAINT FK_ESTOQUE_EMPRESA FOREIGN KEY (ID_EMPRESA) REFERENCES TB_EMPRESA (ID_EMPRESA); 
ALTER TABLE TB_USUARIO ADD CONSTRAINT FK_USUARIO_EMPRESA FOREIGN KEY (ID_EMPRESA) REFERENCES TB_EMPRESA(ID_EMPRESA);